# Generated by Django 4.1.7 on 2023-02-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_album_table_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='reciters',
        ),
    ]
